### ISSUE TITLE
Home Network Prefs

### ISSUE THREAD

**Issue by Twoure** [coryo/DumbTools-for-Plex#1]
When sharing channels with other users in a Home Network, normally the Prefs section of each channel is hidden from everyone but the Plex account holder.  Your DumbPrefs don't account for this and allow other users to change Prefs.

Would like to see your DumbPrefs follow the same rules, that way unwanted users cannot changes a channels preferences.  Maybe even make this an option?

Otherwise, thanks for this tool.

**Comment by coryo** [comment]
I pushed an update that should accomplish this.

It's using the Plex Token of the client to access the preferences, I think any user that shouldn't be able to see the preferences should get a 401 response on `/:/plugins/{identifier}/prefs`. So now it won't add the directory object if that happens.

I have to import urllib2 though because using the plex HTTP.Request seems to add its own headers when you make a request to a plex server.

**Comment by Twoure** [comment]
Wow, that was quick. Thanks for the update, I'll try this out as soon as possible.

**Comment by Twoure** [comment]
Sorry was busy, Testing now.

**Comment by Twoure** [comment]
Seems to work as expect now.
From log file:

```
ERROR (DumbTools:99) - DumbPrefs: this user cant access prefs: HTTP Error 401: Unauthorized
```

Thanks

**Edit:** forgot to mention I'm running PMS on Ubuntu 14.04 Version 0.9.15.1, thought it might be useful for you to know
